[package]
name = "kasumi"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.10.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
thiserror = "2.0.12"
uuid = "1.17.0"
pumpkin-nbt = { git = "https://github.com/Pumpkin-MC/Pumpkin.git" }
