[package]
name = "kasumi-network"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.10.1"
tokio = { version = "1.45.1", features = ["io-util", "net"] }

# self crates dependencies
kasumi-protocol = { path = "../kasumi-protocol" }
thiserror = "2.0.12"
